name: Kube Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Kubernetes version'
        required: true
        type: string
      latest:
        description: 'Push as latest'
        required: true
        default: false
        type: boolean

concurrency: 
  group: ${{ github.ref_name }}-release-${{ inputs.version }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  vanilla-release:
    strategy:
      matrix:
        what:
        - kube-apiserver
        - kube-controller-manager
        arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
        user:
        - 0
        - 65534
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: kubernetes/kubernetes
        ref: ${{ inputs.version }}
        path: kubernetes
        token: ${{ secrets.GIT_HUB_TOKEN }}
        github-server-url: https://github.com
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Patch Kubernetes
      run: |
        (cd kubernetes ; git apply ${{ github.workspace }}/kubernetes-${{ inputs.version }}.patch)
        (cd kubernetes ; git apply ${{ github.workspace }}/build-${{ inputs.version }}.patch)
        sed -i 's~WHAT="${CMD_TARGETS}"~WHAT="staging/src/k8s.io/component-base/logs/kube-log-runner cmd/${{ matrix.what }} cmd/kubectl"~' ${{ github.workspace }}/kubernetes/build/release-images.sh
        sed -i 's~KUBE_BUILD_PLATFORMS="${KUBE_SERVER_PLATFORMS\[\*\]}"~KUBE_BUILD_PLATFORMS="linux/${{ matrix.arch }}"~' ${{ github.workspace }}/kubernetes/build/release-images.sh
        sed -i 's~$(kube::util::host_arch)~${{ matrix.arch }}~' ${{ github.workspace }}/kubernetes/hack/lib/golang.sh
        sed -i 's~$(kube::golang::server_image_targets)~staging/src/k8s.io/component-base/logs/kube-log-runner cmd/${{ matrix.what }} cmd/kubectl~' ${{ github.workspace }}/kubernetes/hack/lib/golang.sh
        sed -i 's~$(kube::build::get_docker_wrapped_binaries)~"${{ matrix.what }},${'$(echo -n ${{ matrix.what }} | tr "a-z-" "A-Z_")'_BASE_IMAGE}"~' ${{ github.workspace }}/kubernetes/build/lib/release.sh
    - name: Build Kubernetes images
      run: make -C kubernetes release-images
      env:
        KUBE_FASTBUILD: "true"
        KUBE_GIT_TREE_STATE: clean
        KUBE_GIT_VERSION: ${{ inputs.version }}
        KUBE_RELEASE_RUN_TESTS: n
        KUBE_BUILD_PLATFORMS: linux/${{ matrix.arch }}
        KUBE_DOCKER_REGISTRY: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}
        KUBE_APISERVER_BASE_IMAGE: registry.access.redhat.com/ubi9/ubi-micro:latest
        KUBE_CONTROLLER_MANAGER_BASE_IMAGE: registry.access.redhat.com/ubi9/ubi-micro:latest
    - name: Set image user
      if: ${{ matrix.user != 0 }}
      run: |
        docker tag ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}-${{ matrix.arch }}:${{ inputs.version }} local/rootless:${{ inputs.version }}
        echo -e "FROM local/rootless:${{ inputs.version }}\nUSER 65534" | docker build --pull=false -t ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}-${{ matrix.arch }}:${{ inputs.version }} -
    - name: Push images
      if: ${{ ! inputs.latest }}
      run: |
        docker tag ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}-${{ matrix.arch }}:${{ inputs.version }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-${{ matrix.arch }}${{ matrix.user != 0 && '-rootless' || '' }}
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-${{ matrix.arch }}${{ matrix.user != 0 && '-rootless' || '' }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker tag ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}-${{ matrix.arch }}:${{ inputs.version }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:latest
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:latest
  vanilla-manifest:
    strategy:
      matrix:
        what:
        - kube-apiserver
        - kube-controller-manager
        user:
        - 0
        - 65534
    needs: vanilla-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Pull images
      run: |
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-amd64${{ matrix.user != 0 && '-rootless' || '' }}
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-ppc64le${{ matrix.user != 0 && '-rootless' || '' }}
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-s390x${{ matrix.user != 0 && '-rootless' || '' }}
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-arm64${{ matrix.user != 0 && '-rootless' || '' }}
    - name: Create manifest
      run: |
        docker manifest create ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.latest && 'latest' || inputs.version }}${{ matrix.user != 0 && '-rootless' || '' }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-amd64${{ matrix.user != 0 && '-rootless' || '' }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-ppc64le${{ matrix.user != 0 && '-rootless' || '' }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-s390x${{ matrix.user != 0 && '-rootless' || '' }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}-arm64${{ matrix.user != 0 && '-rootless' || '' }}
    - name: Push manifest
      if: ${{ ! inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:${{ inputs.version }}${{ matrix.user != 0 && '-rootless' || '' }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/${{ matrix.what }}:latest
  vcluster-release:
    strategy:
      matrix:
        arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
    needs: vanilla-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Create release
      run: docker buildx build --load --platform linux/${{ matrix.arch }} --build-arg VERSION=${{ inputs.version }} --build-arg ARCH=${{ matrix.arch }} -t ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-${{ matrix.arch }} .
      env:
        DOCKER_CLI_EXPERIMENTAL: enabled
    - name: Push release
      if: ${{ ! inputs.latest }}
      run: |
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-${{ matrix.arch }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker tag ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:latest
        docker push --platform linux/${{ matrix.arch }} ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:latest
  vcluster-manifest:
    needs: vcluster-release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v4
    - name: Login to registry
      uses: docker/login-action@v3
      with:
        registry: ${{ vars.REGISTRY }}
        username: ${{ vars.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_TOKEN }}
    - name: Pull images
      run: |
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-amd64
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-ppc64le
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-s390x
        docker pull ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-arm64
    - name: Create manifest
      run: |
        docker manifest create ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.latest && 'latest' || inputs.version }} \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-amd64 \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-ppc64le \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-s390x \
        ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}-arm64
    - name: Push manifest
      if: ${{ ! inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:${{ inputs.version }}
    - name: Push latest
      if: ${{ inputs.latest }}
      run: |
        docker manifest push ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/kubernetes:latest
